### ISSUE TITLE
Erro na instalação ao criar o banco de dados

### ISSUE THREAD

**Issue by MtheusR** [cleitonme/izing.local#1]
Ao criar o banco ele da esse erro: 6edb618101526ff5dd614534a6da4beb192de0402f426abe2091690508daf920

E depois para, não acontece mais nada. Estou utilizando o WSL2 para realizar o procedimento. Teria algum vídeo fazendo esse procedimento?

**Comment by cleitonme** [comment]
foi testado ubuntu conforme descrição outros sistemas não sei o compartamento
