### ISSUE TITLE
Frontend não abre

### ISSUE THREAD

**Issue by Brun0kill** [cleitonme/izing.local#2]
Instalação ocorreu tudo ok, entrando no ip do backend entra certo e manda ir pro front, no portainer tudo certo também, porém quando vou pro front ele nao abre, pagina indisponivel
![err](https://github.com/user-attachments/assets/17ee2d16-dc44-421c-9e72-b7e5cbabdcf1)

**Comment by Brun0kill** [comment]
![image](https://github.com/user-attachments/assets/dc2bc0aa-7f31-4cda-8265-7b995b621469)
![image](https://github.com/user-attachments/assets/3fed4a9f-7b33-4590-aec3-7f061c681b82)

**Comment by cleitonme** [comment]
Talvez não deu algum confrito porta 80... Teria ir server.js da pasta frontend tenta outro porta e reiniciar, ver se tem firewall pode ser ele tambem
